### ISSUE TITLE
Not a good generation

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicWorlds#1]
Hello, 
I have found an issue with the plugin (version 1.3-snapshot, build 229), it doesn't generate the alternate world correctly. I found this error log in the console :
[22:26:11 INFO]: Elsopeen issued server command: /magicw load
[22:26:11 INFO]: [MagicWorlds] Customizing world Utopia
[22:26:11 INFO]: [MagicWorlds] Adding items populator to Utopia
[22:26:11 INFO]: [MagicWorlds] Customizing world Oblivion
[22:26:11 INFO]: [MagicWorlds] Adding replace populator to Oblivion
[22:26:11 INFO]: [MagicWorlds] Adding items populator to Oblivion

org.bukkit.command.CommandException: Unhandled exception executing command 'magicw' in plugin MagicWorlds v1.3-SNAPSHOT
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_openmod.jar:git-Bukkit-e1ebe52]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[minecraft_openmod.jar:git-Bukkit-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[minecraft_openmod.jar:git-Bukkit-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [minecraft_openmod.jar:git-Bukkit-e1ebe52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NoSuchMethodError: com.elmakers.mine.bukkit.entity.EntityData.parseEntityType(Ljava/lang/String;)Lorg/bukkit/entity/EntityType;
at com.elmakers.mine.bukkit.magicworlds.spawn.SpawnRule.load(SpawnRule.java:41) ~[?:?]
at com.elmakers.mine.bukkit.magicworlds.spawn.builtin.CastRule.load(CastRule.java:35) ~[?:?]
at com.elmakers.mine.bukkit.magicworlds.spawn.MagicSpawnHandler.load(MagicSpawnHandler.java:68) ~[?:?]
at com.elmakers.mine.bukkit.magicworlds.MagicWorld.load(MagicWorld.java:79) ~[?:?]
at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.load(MagicWorldsController.java:74) ~[?:?]
at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.onCommand(MagicWorldsPlugin.java:193) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_openmod.jar:git-Bukkit-e1ebe52]
... 15 more

And if you need, here is my config file : 
worlds:
  Utopia:
    chunk_generate:
        items:
          class: MagicChestPopulator
          base_probability:
            0: 100
            1: 80
            2: 2
          item_probability:
            fireball: 200
            fire: 100
            fire|2: 10
            flamethrower: 100
            lava: 75
            lightning: 50
            boon: 15
            grenade: 10
  Oblivion:
      copy: Utopia
      entity_spawn:

```
      rabbit:
        target_type: rabbit
        probability: 0.05
        min_y: 63
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        class: CastRule
        spells:
          - defender material quartz_block seed_radius 2

      skeleton_1_defender:
        target_type: skeleton
        probability: 0.05
        min_y: 63
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        class: CastRule
        spells:
          - defender material mossy_cobblestone seed_radius 2

      creeper_1_hunter:
        target_type: creeper
        probability: 0.3
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material stained_clay seed_radius 2
      creeper_2_hunter:
        target_type: creeper
        probability: 0.5
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material packed_ice seed_radius 2
      creeper_3_virus:
        target_type: creeper
        probability: 0.05
        y_offset: 24
        min_y: 63
        allow_indoors: false
        cooldown: 10000
        class: CastRule
        spells:
          - virus material obsidian seed_radius 3

      zombie_1_hunter:
        target_type: zombie
        probability: 0.3
        y_offset: 6
        min_y: 63
        class: CastRule
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material huge_mushroom_1 seed_radius 2
      zombie_2_hunter:
        target_type: zombie
        probability: 0.5
        y_offset: 6
        min_y: 63
        class: CastRule
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material huge_mushroom_2 seed_radius 2
      zombie_3_hunter:
        target_type: zombie
        probability: 0.7
        y_offset: 6
        min_y: 63
        class: CastRule
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material stained_clay seed_radius 2
      zombie_4_hunter:
        target_type: zombie
        probability: 0.8
        y_offset: 6
        min_y: 63
        class: CastRule
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material wool seed_radius 2
      zombie_5_virus:
        target_type: zombie
        probability: 0.05
        y_offset: 24
        min_y: 63
        class: CastRule
        allow_indoors: false
        cooldown: 10000
        spells:
          - virus material huge_mushroom_1 seed_radius 3
      zombie_6_defender:
        target_type: zombie
        probability: 0.1
        min_y: 63
        class: CastRule
        y_offset: 12
        allow_indoors: false
        cooldown: 10000
        spells:
          - defender material hay_block seed_radius 3

      spider_1_hunter:
        target_type: spider
        probability: 0.3
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material melon_block seed_radius 2
      spider_2_hunter:
        target_type: spider
        probability: 0.4
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material pumpkin seed_radius 2
      spider_3_hunter:
        target_type: spider
        probability: 0.5
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material soul_sand seed_radius 2
      spider_4_hunter:
        target_type: spider
        probability: 0.5
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material clay seed_radius 2
      spider_5_virus:
        target_type: spider
        probability: 0.05
        min_y: 63
        class: CastRule
        y_offset: 24
        allow_indoors: false
        cooldown: 10000
        spells:
          - virus material melon_block seed_radius 3
      spider_6_worm:
        target_type: spider
        probability: 0.05
        min_y: 63
        class: CastRule
        y_offset: 32
        allow_indoors: false
        cooldown: 10000
        spells:
          - worm material clay seed_radius 3

      enderman_1_hunter:
        target_type: enderman
        probability: 0.2
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material prismarine seed_radius 2
      enderman_2_hunter:
        target_type: enderman
        probability: 0.3
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material log seed_radius 2
      enderman_3_hunter:
        target_type: enderman
        probability: 0.4
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material log_2 seed_radius 2
      enderman_4_hunter:
        target_type: enderman
        probability: 0.5
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material wool seed_radius 2
      enderman_5_hunter:
        target_type: enderman
        probability: 0.6
        min_y: 63
        class: CastRule
        y_offset: 6
        allow_indoors: false
        cooldown: 10000
        spells:
          - hunter material obsidian seed_radius 2
      enderman_6_worm:
        target_type: enderman
        probability: 0.05
        min_y: 63
        class: CastRule
        y_offset: 24
        allow_indoors: false
        cooldown: 10000
        spells:
          - worm material log seed_radius 3
      enderman_7_worm:
        target_type: enderman
        probability: 0.01
        min_y: 63
        class: CastRule
        y_offset: 32
        allow_indoors: false
        cooldown: 10000
        spells:
          - worm material obsidian seed_radius 3
      enderman_8_giant:
        target_type: enderman
        probability: 0.3
        min_y: 63
        class: ReplaceRule
        replace_type: giant

 # None of these are likely to spawn here since there is no grass!

      horse_1_skeleton_horse:
        target_type: horse
        probability: 0.5
        min_y: 63
        class: ReplaceRule
        replace_type: horse
        replace_sub_type: skeleton_horse

      chicken_999_enderman:
        target_type: chicken
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      pig_999_enderman:
        target_type: pig
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      sheep_999_enderman:
        target_type: sheep
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      pig_999_enderman:
        target_type: pig
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      horse_999_enderman:
        target_type: horse
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      cow_998_mushroomcow:
        target_type: cow
        probability: 0.8
        min_y: 63
        class: ReplaceRule
        replace_type: mushroomcow
      cow_999_enderman:
        target_type: cow
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman

   # Default fallbacks

      creeper_999_enderman:
        target_type: creeper
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      zombie_999_enderman:
        target_type: zombie
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      skeleton_999_enderman:
        target_type: skeleton
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      spider_999_enderman:
        target_type: spider
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      rabbit_999_enderman:
        target_type: rabbit
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman

   # Other Mob Replacement

      villager_1_pigman:
        class: ReplaceRule
        probability: 1.0
        target_type: villager
        replace_type: pigzombie

      slime_1_lavaslime:
        target_type: slime
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: lavaslime

      bat_1_blaze:
        target_type: bat
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: blaze

  chunk_generate:
    replace:
      class: ReplacePopulator
      replace:
        grass: mycel
        dirt: netherrack
        stone: ender_stone
        leaves: glowstone
        leaves_2: stained_glass|*
        log: stained_glass_pane|*
        log_2: glowstone
        hard_clay: stained_glass|12
        water: stained_glass|9
        stationary_water: stained_glass|3
        lava: stained_glass|13
        stationary_lava: stained_glass|1
        sandstone: stained_clay:10
        stained_clay: stained_glass:*
        gravel: soul_sand
        sand: sand:1
        cactus: nether_fence
        long_grass: brown_mushroom
        yellow_flower: red_mushroom
        red_rose: torch
        wood: brick
        double_plant: cobble_wall
        fence: iron_fence
        iron_fence: cobble_wall
        cobblestone: nether_brick
        mossy_cobblestone: iron_block
        mob_spawner: diamond_block
        glass: stained_glass|10
        thin_glass: stained_glass_pane|9
        ice: stained_glass|11
        packed_ice: stained_glass|11
        clay: stained_clay|10
        snow_block: quartz_block
        coal_ore: quartz_ore
        diamond_ore: quartz_ore
        emerald_ore: quartz_ore
        iron_ore: quartz_ore
        gold_ore: quartz_ore
        wool: log|2
        pumpkin: jack_o_lantern
        melon_block: torch
        huge_mushroom_1: stained_glass:*
        huge_mushroom_2: stained_glass_pane:*
    items:
      class: MagicChestPopulator
      base_probability:
        0: 20
        1: 70
        2: 20
        3: 5
      item_probability:
        phase: 50
        blast|3: 60
        grenade: 1
        peek: 100
        breach: 100
        blink|3: 50
        emp: 10
```

  Oblivion_backup:
      entity_spawn:

```
 # None of these are likely to spawn here since there is no grass!

      horse_1_skeleton_horse:
        target_type: horse
        probability: 0.5
        min_y: 63
        class: ReplaceRule
        replace_type: horse
        replace_sub_type: skeleton_horse
      horse_2_undead_horse:
        target_type: horse
        probability: 1
        min_y: 63
        class: ReplaceRule
        replace_type: horse
        replace_sub_type: undead_horse

      chicken_999_enderman:
        target_type: chicken
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      pig_999_enderman:
        target_type: pig
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      sheep_999_enderman:
        target_type: sheep
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      pig_999_enderman:
        target_type: pig
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      horse_999_enderman:
        target_type: horse
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      cow_998_mushroomcow:
        target_type: cow
        probability: 0.8
        min_y: 63
        class: ReplaceRule
        replace_type: mushroomcow
      cow_999_enderman:
        target_type: cow
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman

   # Default fallbacks

      creeper_999_enderman:
        target_type: creeper
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      zombie_999_enderman:
        target_type: zombie
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      skeleton_999_enderman:
        target_type: skeleton
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman
      spider_999_enderman:
        target_type: spider
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: enderman

   # Other Mob Replacement

      villager_1_pigman:
        class: ReplaceRule
        probability: 1.0
        target_type: villager
        replace_type: pigzombie

      slime_1_lavaslime:
        target_type: slime
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: lavaslime

      bat_1_blaze:
        target_type: bat
        probability: 1.0
        min_y: 63
        class: ReplaceRule
        replace_type: blaze

  chunk_generate:
    replace:
      class: ReplacePopulator
      replace:
        grass: mycel
        dirt: netherrack
        stone: ender_stone
        leaves: glowstone
        leaves_2: stained_glass|*
        log: stained_glass_pane|*
        log_2: glowstone
        hard_clay: stained_glass|12
        water: stained_glass|9
        stationary_water: stained_glass|3
        lava: stained_glass|13
        stationary_lava: stained_glass|1
        sandstone: stained_clay:10
        stained_clay: stained_glass:*
        gravel: soul_sand
        sand: sand:1
        cactus: nether_fence
        long_grass: brown_mushroom
        yellow_flower: red_mushroom
        red_rose: torch
        wood: brick
        double_plant: cobble_wall
        fence: iron_fence
        iron_fence: cobble_wall
        cobblestone: nether_brick
        mossy_cobblestone: iron_block
        mob_spawner: diamond_block
        glass: stained_glass|10
        thin_glass: stained_glass_pane|9
        ice: stained_glass|11
        packed_ice: stained_glass|11
        clay: stained_clay|10
        snow_block: quartz_block
        coal_ore: quartz_ore
        diamond_ore: quartz_ore
        emerald_ore: quartz_ore
        iron_ore: quartz_ore
        gold_ore: quartz_ore
        wool: log|2
        pumpkin: jack_o_lantern
        melon_block: torch
        huge_mushroom_1: stained_glass:*
        huge_mushroom_2: stained_glass_pane:*
        prismarine: stained_clay:*
        sea_lantern: redstone_lamp_on
        gold_block: diamond_block
```

Hoping you could help me resolving my issue,
best regards, 
Elsopeen
