### ISSUE TITLE
Trees at chunk boundaries not handled properly

### ISSUE THREAD

**Issue by sargunv** [elBukkit/MagicWorlds#2]
I tried creating a new world using this plugin, and noticed that trees with leaves across chunk boundaries don't get their blocks replaced properly.

![Screenshot](https://cloud.githubusercontent.com/assets/1320357/21079530/5b700a3e-bf62-11e6-9ab2-cc626b9847af.png)

The relevant portion of my config looks like this:

```yaml
world_other:
  copy: world
  chunk_generate:
    replace:
      class: ReplacePopulator
      replace:
        log: obsidian
        log_2: obsidian
        leaves: air
        leaves_2: air
        #... and many more replacements
```

I'm using the latest dev build of MagicWorlds on the latest build of SpigotMC.
