### ISSUE TITLE
Replacing water with lava creates obsidian oceans instead

### ISSUE THREAD

**Issue by sargunv** [elBukkit/MagicWorlds#3]
I tried replacing water with lava to get lava oceans/rivers/lakes in my alternate world, but instead it generates obsidian oceans/rivers/lakes.

```yaml
worlds:
  world_other:
      copy: world
      chunk_generate:
        replace:
          class: ReplacePopulator
          replace:
            stationary_water: stationary_lava
            water: lava
```
